### ISSUE TITLE
Error reading "Tassel" genotype file

### ISSUE THREAD

**Issue by nrlabonte** [AgResearch/KGD#39]
Hello,
I converted a .vcf SNP genotype file to the "Tassel" formatted tab file using the included Python script (which is great, thank you!).  I can't GBS-Chip-Gmatrix.R to import it correctly, though.  When I run the following commands: 

> genofile <- "LxMsiF2_maf_test100.vcf.ra.tab"
> gform <- "Tassel"
> source("GBS-Chip-Gmatrix.R")

I get the following messages:

Read 411 items
Error in scan(genofilefn0, skip = 1, sep = "\t", what = c(list(chrom = "",  : 
  scan() expected 'a real', got '0,0'

I ran GBS-Chip-Gmatrix.R using a different converted .vcf from our lab, from the same SNP-calling pipeline, and it worked fine.  Do you know what the issue might be here?  The file that doesn't work is attached.  
Thank you so much for your help,
Nick 
[LxMsiF2_maf_test100.vcf.ra.tab.txt](https://github.com/AgResearch/KGD/files/5052973/LxMsiF2_maf_test100.vcf.ra.tab.txt)

**Comment by doddsk** [comment]
This was caused by some sample identifiers having single quotes (at the end). v0.9.5, uploaded today, will treat these as text characters. Previously they were interpreted as quotes around text (the default behaviour of the scan function in R).

Did the "different converted .vcf" conversion process remove those quotes?

Thanks for highlighting this issue.

**Comment by nrlabonte** [comment]
Ah, that makes sense.  My other .vcf (the one that worked) didn't have those single quotes.  Thank you for the quick response!
